name: OctoPetShopAppBuild

on:
  workflow_dispatch:
  push:
    branches:
    - main
  schedule:
    - cron: '* * * * *'
env:
  solution: '**/*.sln'
  buildPlatform: Any CPU
  buildConfiguration: Release
jobs:
  OctoPetShopBuild:
    runs-on: windows-latest
    steps:
    # We take a copy of the files within the repo and put them in our working directory
    - uses: actions/checkout@v2
    # We install the latest Octopus Deploy CLI
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
